version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    container_name: "backend"
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: backend.local
  frontend:
      container_name: "frontend"
      restart: always
      build: ../next-starter/
      ports:
        - '3000:3000'
      command: yarn dev
      volumes:
        - ../next-starter:/src
        - /src/node_modules
      depends_on:
        - backend
